name: npm test
on: 
  workflow_dispatch:
               
jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4.1.6
      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
      - name: Run nodejs application installation
        run: npm install
      - name: Run nodejs tests
        run: npm test
