name: interact with Github API
on: 
  pull_request:

jobs:
  create-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: "Get short sha"
        id: short_sha
        run: echo "sha_short=${FULL_SHA::7}" >> $GITHUB_ENV
        env:
          FULL_SHA: ${{ github.sha }}
      - name: "Create github issue"
        run: |
            curl --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/issues \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --header 'content-type: application/json' \
            --data '{
              "title": "Automated issue for commit: ${{ env.sha_short }}",
              "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ env.sha_short }}_."
              }' \
            --fail
